
@startuml
package "Формы" {
    component ФормаВхода
    component ФормаРегистрации
    component ФормаВопроса
}

package "Модели" {
    component Пользователь
    component Профиль
    component Пост
    component Ответ
    component Тег
}

ФормаВхода --> Пользователь : Проверка входа
ФормаРегистрации --> Пользователь : Создание учетной записи
ФормаВопроса --> Пост : Создание поста
ФормаВопроса --> Тег : Добавление тегов к посту
@enduml
