
@startuml
class Пользователь {
    +имя_пользователя: String
    +электронная_почта: String
}

class Профиль {
    +аватар: String
    +количество_ответов: int
    +время_обновления: DateTime
    +количество_подписчиков: int
}

class Тег {
    +название_тега: String
    +использований: int
}

class Пост {
    +содержимое: String
    +время_создания: DateTime
    +количество_лайков: int
    +количество_ответов: int
    +режим_доступа: String
}

class Ответ {
    +текст_ответа: Text
    +время_создания: DateTime
    +количество_лайков: int
}

class ЛайкПоста {
    +оценка: int
}

class ЛайкОтвета {
    +оценка: int
}

class Подписка {
    +время_создания: DateTime
}

class ФайлПоста {
    +файл: File
}

Пользователь "1" -- "1" Профиль
Профиль "1" -- "*" Пост
Профиль "1" -- "*" Ответ
Профиль "1" -- "*" Профиль : подписчики
Пост "1" -- "*" Ответ
Пост "1" -- "*" ЛайкПоста
Ответ "1" -- "*" ЛайкОтвета
Пост "1" -- "*" Тег
Пост "1" -- "*" ФайлПоста
Профиль "1" -- "*" Подписка : подписчик
Профиль "1" -- "*" Подписка : подписан
@enduml
