
@startuml
skinparam componentStyle rectangle

package "Project Momentum" {
    folder "Web Server" as WebServer
    folder "Django Application" as DjangoApp {
        folder "back" as BackApp {
            file "models.py"
            file "views.py"
            file "forms.py"
            file "urls.py"
            file "admin.py"
            folder "management" as Management {
                folder "commands" as Commands {
                    file "fill_db.py"
                    file "__init__.py"
                }
                file "__init__.py"
            }
            folder "migrations" as Migrations {
                file "0001_initial.py"
                file "0002_remove_answer_correct.py"
                file "0003_remove_post_title.py"
                file "0004_postfile.py"
                file "0005_alter_postfile_file.py"
                file "0006_subscription.py"
                file "0007_post_access_mode.py"
                file "__init__.py"
            }
            folder "templatetags" as TemplateTags {
                file "custom_filters.py"
                file "__init__.py"
            }
        }
        folder "momentum" as CoreApp {
            file "settings.py"
            file "urls.py"
            file "wsgi.py"
            file "asgi.py"
            file "__init__.py"
        }
        folder "templates" as Templates {
            file "index.html"
            file "profile.html"
            file "question.html"
            file "base.html"
        }
        folder "static" as StaticFiles {
            folder "css"
            folder "js"
            folder "img"
        }
    }
    folder "Database (PostgreSQL)" as Database
    folder "Config Files" as Config {
        file "Dockerfile"
        file "docker-compose.yml"
        file ".env"
    }
}

WebServer --> DjangoApp
DjangoApp --> BackApp
BackApp --> Management
BackApp --> Migrations
BackApp --> TemplateTags
DjangoApp --> CoreApp
DjangoApp --> Templates
DjangoApp --> StaticFiles
DjangoApp --> Database
DjangoApp --> Config
@enduml
