
@startuml
skinparam DefaultFontSize 25
skinparam ParticipantFontSize 16
skinparam ActorFontSize 25
skinparam ParticipantPadding 20
skinparam BoxPadding 25

actor User
participant "Клиент" as Browser
participant "Сервер" as Backend
participant "База Данных" as Database

User -> Browser: Запрос "Подписаться"
activate Browser
Browser -> Backend: Отправка запроса на подписку
activate Backend
Backend -> Database: Проверить, вошел ли пользователь
activate Database
Database --> Backend: Ответ (Пользователь не аутентифицирован)
deactivate Database


Backend -> Browser: Перенаправление на страницу входа
deactivate Backend
Browser -> User: Пожалуйста войдите в аккаунт
deactivate Browser

User -> Browser: Ввод учетных данных
activate Browser
Browser -> Backend: Отправка учетных данных
activate Backend
Backend -> Database: Проверка учетных данных
activate Database
Database --> Backend: Учетные данные верны
deactivate Database
Backend -> Browser: Перенаправление обратно в профиль
deactivate Backend

Browser -> Backend: Повторный запрос на подписку
activate Backend
Backend -> Database: Проверить наличие подписки
activate Database
Database --> Backend: Подписка отсутствует
deactivate Database
Backend -> Database: Создание подписки
activate Database
Database --> Backend: Подписка создана
deactivate Database
Backend -> Browser: Уведомление об успешной подписке
deactivate Backend
Browser -> User: Вы подписались на пользователя
deactivate Browser
@enduml
