# Generated by Django 5.1.2 on 2024-11-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_remove_answer_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
