# Generated by Django 5.1.2 on 2024-11-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_postfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
