# Generated by Django 5.1.2 on 2024-11-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='access_mode',
            field=models.CharField(choices=[('public', 'Общий доступ'), ('subscribers', 'Только для подписчиков')], default='public', max_length=12),
        ),
    ]
