
@startuml
class Пользователь {
    +username: String
    +email: String
}

class Профиль {
    +avatar_path: String
    +answers_count: int
    +followers_count: int
}

class Пост {
    +content: String
    +created_time: DateTime
    +likes_count: int
    +answers_count: int
}

class Ответ {
    +answer: Text
    +created_time: DateTime
    +likes_count: int
}

Пользователь "1" -- "1" Профиль
Профиль "1" -- "*" Пост
Профиль "1" -- "*" Ответ
Профиль "1" -- "*" Профиль : подписчики
Пост "1" -- "*" Ответ
@enduml
