
@startuml
actor "Неаунтефицированный пользователь" as noAuthUser
actor "Зарегестрированный пользователь" as AuthUser
actor "Создатель поста" as Creator

noAuthUser -> (Вход в систему)
noAuthUser -> (Регистрация)
noAuthUser  -> (Просмотр ленты новостей)

AuthUser  -> (Поставить лайк)
AuthUser  -> (Ответить на вопрос)
AuthUser -> (Подписаться на пользователя)
AuthUser  -> (Поиск контента)

Creator -> (Редактирование)
Creator-> (Удаление)
@enduml
