
@startuml
actor "Пользователь" as User
actor "Администратор" as Admin

User -> (Вход в систему)
User -> (Регистрация)
User -> (Просмотр поста)
User -> (Поставить лайк)
User -> (Ответить на вопрос)
User -> (Подписаться на пользователя)
User -> (Поиск контента)

Admin -> (Управление постами)
Admin -> (Удаление постов)
@enduml
